version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "80:3000"
    environment:
      - NODE_ENV
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:3.6.2
    ports:
      - "27017:27017"
  redis:
    image: redis:4.0.7
    ports:
      - "6379:6379"
